# Generated by Django 3.0.3 on 2020-02-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='title',
            field=models.CharField(default='Default Title', max_length=20),
        ),
    ]
