# Generated by Django 3.0.3 on 2020-02-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_savegame_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savegame',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
